index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: dashboard
        permanent: true

dashboard:
    path: /dashboard
    defaults: { _controller: AppBundle:Page:Dashboard }
